spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    url: 'jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=4;TRACE_LEVEL_SYSTEM_OUT=3'
management:
  endpoints:
    web:
      base-path: '/status'
      exposure:
        include: '*'